# Generated by Django 3.0.1 on 2019-12-18 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['num'], 'verbose_name': 'Билет', 'verbose_name_plural': 'Билеты'},
        ),
    ]
